/*
 * generated by Xtext 2.14.0
 */
package com.m1ice.fsm.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.m1ice.fsm.dsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import com.m1ice.fsm.dsl.services.MyDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFSMAccess().getAlternatives_3(), "rule__FSM__Alternatives_3");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getFSMAccess().getGroup(), "rule__FSM__Group__0");
			builder.put(grammarAccess.getFSMAccess().getGroup_3_0(), "rule__FSM__Group_3_0__0");
			builder.put(grammarAccess.getFSMAccess().getGroup_3_0_2(), "rule__FSM__Group_3_0_2__0");
			builder.put(grammarAccess.getFSMAccess().getGroup_3_2(), "rule__FSM__Group_3_2__0");
			builder.put(grammarAccess.getFSMAccess().getGroup_3_3(), "rule__FSM__Group_3_3__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_2(), "rule__Transition__Group_2__0");
			builder.put(grammarAccess.getInitalStateAccess().getGroup(), "rule__InitalState__Group__0");
			builder.put(grammarAccess.getFinalStateAccess().getGroup(), "rule__FinalState__Group__0");
			builder.put(grammarAccess.getFSMAccess().getNameAssignment_1(), "rule__FSM__NameAssignment_1");
			builder.put(grammarAccess.getFSMAccess().getStateAssignment_3_0_1(), "rule__FSM__StateAssignment_3_0_1");
			builder.put(grammarAccess.getFSMAccess().getStateAssignment_3_0_2_1(), "rule__FSM__StateAssignment_3_0_2_1");
			builder.put(grammarAccess.getFSMAccess().getTransitionAssignment_3_1(), "rule__FSM__TransitionAssignment_3_1");
			builder.put(grammarAccess.getFSMAccess().getStateAssignment_3_2_1(), "rule__FSM__StateAssignment_3_2_1");
			builder.put(grammarAccess.getFSMAccess().getStateAssignment_3_3_1(), "rule__FSM__StateAssignment_3_3_1");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getStateStartAssignment_2_0(), "rule__Transition__StateStartAssignment_2_0");
			builder.put(grammarAccess.getTransitionAccess().getStateEndAssignment_2_2(), "rule__Transition__StateEndAssignment_2_2");
			builder.put(grammarAccess.getInitalStateAccess().getNameAssignment_1(), "rule__InitalState__NameAssignment_1");
			builder.put(grammarAccess.getFinalStateAccess().getNameAssignment_1(), "rule__FinalState__NameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
