/**
 * generated by Xtext 2.14.0
 */
package com.m1ice.fsm.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.m1ice.fsm.dsl.MyDslRuntimeModule;
import com.m1ice.fsm.dsl.MyDslStandaloneSetup;
import com.m1ice.fsm.dsl.ide.MyDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyDslIdeSetup extends MyDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyDslRuntimeModule _myDslRuntimeModule = new MyDslRuntimeModule();
    MyDslIdeModule _myDslIdeModule = new MyDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_myDslRuntimeModule, _myDslIdeModule));
  }
}
