/**
 * generated by Xtext 2.14.0
 */
package com.m1ice.fsm.dsl.ide;

import com.m1ice.fsm.dsl.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
