/*
 * generated by Xtext 2.14.0
 */
package com.m1ice.fsm.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
