/*
 * generated by Xtext 2.14.0
 */
package com.m1ice.fsm.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MyDslUiModule extends AbstractMyDslUiModule {
}
