/**
 * generated by Xtext 2.14.0
 */
package com.m1ice.fsm.dsl;

import com.m1ice.fsm.dsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
